# 🛡️ AI Governance Config by ProdMoh

> One-click AI governance rules for Cursor, Windsurf, GitHub Copilot, and any AI coding assistant.

This repository contains **governance configuration files** generated by [ProdMoh](https://prodmoh.com) — ensuring your AI-assisted development follows security, compliance, and architectural best practices.

---

## 🚀 How It Works

### Step 1: Create a PRD on ProdMoh

1. Go to [prodmoh.com](https://prodmoh.com) and sign in
2. Click **"New PRD"** (Product Requirements Document)
3. Describe your feature or product idea
4. ProdMoh generates a complete PRD with:
   - Product vision & strategy
   - Target audience & personas
   - Feature requirements
   - Success metrics

### Step 2: Generate User Stories

1. Open your PRD
2. Click **"Generate User Stories"**
3. ProdMoh creates detailed user stories with:
   - Acceptance criteria
   - Technical considerations
   - Edge cases

### Step 3: Configure AI Governance

1. From your PRD or User Story, click **"Governance Config"**
2. Select your **industry preset**:
   - 🏥 **Healthcare** → HIPAA + OWASP security, audit logging
   - 💰 **Fintech** → SOC2 + PCI-DSS, structured logging
   - 💻 **General SaaS** → OWASP Top 10, clean architecture
3. Customize additional options:
   - Design Pattern (MVC, Clean, Hexagonal)
   - Security Framework
   - Logging Standard
   - Testing Strategy

### Step 4: Push Directly to GitHub

1. Click **"Export Governance Config"** → **"Push to GitHub"**
2. **First time only:** Connect your GitHub account (OAuth)
3. Enter your repository (e.g., `your-org/backend-service`)
4. Select the file type:
   - `.cursorrules` for Cursor
   - `.windsurfrules` for Windsurf
   - `copilot-instructions.md` for GitHub Copilot
   - `.moh` for universal AI assistants
5. Click **"Push to Repo"** → ✅ Done!

---

## 📁 File Formats

| File | AI Tool | Location |
|------|---------|----------|
| `.cursorrules` | [Cursor](https://cursor.sh) | Project root |
| `.windsurfrules` | [Windsurf](https://codeium.com/windsurf) | Project root |
| `copilot-instructions.md` | GitHub Copilot | `.github/` folder |
| `.moh` | Any AI assistant | Project root |

---

## 🔐 What's Inside a Governance Config?

Each config file contains:
ProdMoh Governance Configuration
Project Context
PRD/User Story context from your product requirements
Architecture & Design
Design patterns (Clean Architecture, MVC, etc.)
Code structure guidelines
Module organization
Security Framework
OWASP Top 10 protections
Input validation rules
Authentication/Authorization patterns
PII handling guidelines
Logging & Observability
Structured logging format
Audit trail requirements
Error handling patterns
Testing Strategy
Test coverage expectations
TDD/BDD guidelines
Integration test patterns
---
## 🏢 Industry Presets
### Healthcare (HIPAA)
- PHI encryption requirements
- Audit trail logging for all data access
- Access control patterns
- Data retention compliance
### Fintech (SOC2/PCI-DSS)
- Transaction logging
- Encryption at rest and in transit
- Secure credential handling
- Rate limiting and fraud detection
### General SaaS (OWASP)
- Input sanitization
- SQL injection prevention
- XSS protection
- CSRF tokens
---
## 💡 Why Use ProdMoh Governance?
| Problem | Solution |
|---------|----------|
| 10 engineers writing 10 different prompts | One standardized config for the whole team |
| AI generating insecure code | Security baked into every prompt |
| No visibility into AI instructions | Full history and audit trail |
| Manual copy-paste workflow | Direct GitHub integration |
---
## 🔗 Links
- **Website:** [prodmoh.com](https://prodmoh.com)
- **AI Coding Prompts:** [prodmoh.com/ai-coding-prompts](https://prodmoh.com/ai-coding-prompts)
- **Documentation:** Coming soon
---
## 📄 License
These governance configurations are generated by [ProdMoh](https://prodmoh.com). 
Use them freely in your projects. 
---
<p align="center">
  <strong>Ship secure, compliant code with AI — without the chaos.</strong><br>
  <a href="https://prodmoh.com">Get Started with ProdMoh →</a>
</p>
